export const SHARED_VERSION = '0.1.0' as const;

export {
  CANDLE_SOURCES,
  candleRowToCandle,
  candleSchema,
  candleSourceSchema,
  candleTickSchema,
  type Candle,
  type CandleRow,
  type CandleSource,
  type CandleTick,
} from './candle.js';

export { ERROR_CODES, ERROR_STATUS, isErrorCode, type ErrorCode } from './errors.js';

export {
  EXIT_REASONS,
  FILL_MODELS,
  SIDES,
  execConfigSchema,
  exitReasonSchema,
  fillModelSchema,
  sideSchema,
  type ExecConfigInput,
  type ExitReason,
  type FillModel,
  type Side,
} from './execution.js';

export {
  BACKTEST_WARNINGS,
  COMPARE_MAX_IDS,
  RUNS_DEFAULT_LIMIT,
  RUNS_MAX_LIMIT,
  SEED_MAX,
  TRADES_DEFAULT_LIMIT,
  TRADES_MAX_LIMIT,
  backtestMetricsSchema,
  backtestTradeSchema,
  backtestWarningSchema,
  cancelBacktestResponseSchema,
  compareCurveSchema,
  compareQuerySchema,
  compareResponseSchema,
  createBacktestBodySchema,
  createBacktestResponseSchema,
  equityPointSchema,
  equityResponseSchema,
  listBacktestsQuerySchema,
  listBacktestsResponseSchema,
  runDetailSchema,
  runIdParamsSchema,
  runSummarySchema,
  runTimingsSchema,
  timestampBodySchema,
  tradesQuerySchema,
  tradesResponseSchema,
  type BacktestMetricsResponse,
  type BacktestTrade,
  type BacktestWarning,
  type CancelBacktestResponse,
  type CompareQuery,
  type CompareResponse,
  type CreateBacktestBody,
  type CreateBacktestResponse,
  type EquityResponse,
  type ListBacktestsQuery,
  type ListBacktestsResponse,
  type RunDetail,
  type RunSummary,
  type TradesQuery,
  type TradesResponse,
} from './backtest-schemas.js';

export {
  BACKTEST_QUEUE_NAME,
  RUN_STATUSES,
  RUN_CANCEL_TTL_SEC,
  backtestJobSchema,
  runCancelKey,
  runChannel,
  runDoneEventSchema,
  runErrorEventSchema,
  runEventSchema,
  runProgressEventSchema,
  runStatusEventSchema,
  runStatusSchema,
  type BacktestJob,
  type RunEvent,
  type RunProgressEvent,
  type RunStatus,
  type RunStatusEvent,
} from './jobs.js';

export {
  CANDLES_MAX_LIMIT,
  candlesQuerySchema,
  candlesResponseSchema,
  compactCandleSchema,
  coverageGapSchema,
  coverageParamsSchema,
  coverageQuerySchema,
  coverageResponseSchema,
  marketSymbolSchema,
  marketsResponseSchema,
  symbolSchema,
  timestampParamSchema,
  type CandlesQuery,
  type CandlesResponse,
  type CoverageResponse,
  type MarketSymbol,
  type MarketsResponse,
} from './api-schemas.js';

export {
  STRATEGY_PARAM_TYPES,
  strategyCatalogSchema,
  strategyMetaSchema,
  strategyParamSchema,
  type StrategyCatalog,
  type StrategyMeta,
  type StrategyParam,
  type StrategyParamType,
} from './strategy-catalog.js';

export {
  InvalidTimestampError,
  TIMEFRAMES,
  alignTs,
  expectedCandleCount,
  isAligned,
  isTimeframe,
  timeframeSchema,
  timeframeToMs,
  type Timeframe,
} from './timeframe.js';
